# Generated by Django 4.2.4 on 2023-08-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_index', models.CharField(max_length=500)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dates')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.demo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.times')),
            ],
        ),
    ]
